substitutions:
  name: bad
  platform: ESP8266 # Shelly 2.5
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953
    voltage:
      id: voltage
    current_a:
      id: current_2
      filters:
        - multiply: 0.1
    current_b:
      id: current_1
      filters:
        - multiply: 0.88
    active_power_a:
      id: power_2
    active_power_b:
      id: power_1
    update_interval: 60s

  - platform: ntc
    sensor: temp_resistance_reading
    id: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 25°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

binary_sensor:
  - platform: gpio
    pin: GPIO16
    id: "ade7953_irq_pin"
    internal: true
  - platform: gpio
    pin:
      number: GPIO13
    id: button1
    name: button1
    on_press:
      then:
        - switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO5
    id: button2
    name: button2
    on_press:
      then:
        - switch.toggle: relay2

switch:
  - platform: gpio
    id: relay1
    name: relay1
    pin: GPIO4
  - platform: gpio
    id: relay2
    name: relay2
    pin: GPIO15
