esphome:
  name: heizung-vorlauf
  platform: ESP8266
  board: esp12e

wifi:
  use_address: heizung_vorlauf

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: 5
  scl: 4

sensor:
  - platform: bme280
    address: 0x76
#    update_interval: 300s
    temperature:
      name: "temperature1"
  - platform: bme280
    address: 0x77
#    update_interval: 300s
    temperature:
      name: "temperature2"
