# Note: this may not be needed if the pull request has been merged.
# Check https://github.com/esphome/esphome/pull/2956 for current status.
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

# Set some variables for convenience
substitutions:
  node_name: ns-display1
  tft_prefix: http://172.28.29.33:8080
  platform: ESP32
  board: esp32dev

esphome:
  name: $node_name

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: "zappa"
  password: "lawqrzvagAKFOPSW958372:--."

# Disable logging
logger:
  baud_rate: 0

# Enable wireless updates
ota:

web_server:
  port: 80

mqtt:
  broker: dipe-pi
  discovery: false
  on_message:
    - topic: ns-display1/upload
      then:
        - lambda: |-
            id(ble_tracker).stop_scan();
            id(disp1).upload_tft();

# Define some outputs
switch:
  # Pin 4 always needs to be on to power up the display
  - platform: gpio
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

# Configure the internal bleeper
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Enable ringtone music support
rtttl:
  id: buzzer
  output: buzzer_out
  
# Configure UART for communicating with the screen
uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
#  baud_rate: 115200

esp32_ble_tracker:
  id: ble_tracker

# Configure the screen itself
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: http://172.28.29.33:8080/x.tft
    on_setup:
      then:
        - rtttl.play: "startup:d=16,o=5,b=180:c,e,g,c6,8p,c,16p,e,c"
        - lambda: id(disp1).send_command_printf("lcd_dev fffb 0002 0000 0020"); # Magic command to avoid 32pixel touchscreen offset on NSPanel (https://github.com/UNUF/nxt-doc/blob/main/Protocols/Full%20Instruction%20Set.md#readme)
        - lambda: id(disp1).send_command_printf("DRAKJHSUYDGBNCJHGJKSHBDN");
