substitutions:
  name: pinpad-haustuer
  platform: ESP32
  board: wemos_d1_mini32

packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device32_base.yaml

matrix_keypad:
  id: keypad
  rows:
    - pin: GPIO22 # R1
    - pin: GPIO02 # R2
    - pin: GPIO16 # R3
    - pin: GPIO21 # R4
  columns:
    - pin: GPIO32 # C1
    - pin: GPIO25 # C2
    - pin: GPIO17 # C3
  # rows:
  #   - pin: GPIO25
  #   - pin: GPIO22
  #   - pin: GPIO32
  #   - pin: GPIO21
  # columns:
  #   - pin: GPIO17
  #   - pin: GPIO16
  #   - pin: GPIO02
  keys: "123456789*0#"
  has_diodes: false

key_collector:
  - id: pincode
    source_id: keypad
    max_length: 20
    end_keys: "#"
    end_key_required: true
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 5s
    on_progress:
      - output.turn_on: buzzer
      - delay: 10ms
      - output.turn_off: buzzer
    on_result:
      - mqtt.publish:
          topic: ${name}/pin
          payload: !lambda 'return x;'
    on_timeout:
      - output.turn_on: buzzer
      - delay: 10ms
      - output.turn_off: buzzer
      - delay: 10ms
      - output.turn_on: buzzer
      - delay: 10ms
      - output.turn_off: buzzer
      - delay: 10ms
      - output.turn_on: buzzer
      - delay: 10ms
      - output.turn_off: buzzer

globals:
  - id: count1
    type: int
  - id: count2
    type: int

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    id: button1
    name: "button1"
    on_press:
      then:
        - lambda: 'id(count1) = 0;'
        - while:
            condition:
              and:
                - binary_sensor.is_on: button1
                - lambda: 'return id(count1) < 3;'
            then:
                - switch.turn_on: relay1
                - delay: 200ms
                - switch.turn_off: relay1
                - lambda: 'id(count1) = id(count1) + 1;'
                - delay: 800ms
  - platform: gpio
    pin:
      number: GPIO23
      mode:
        input: true
        pullup: true
      inverted: true
    id: button2
    name: button2
    on_press:
      then:
        - lambda: 'id(count2) = 0;'
        - while:
            condition:
              and:
                - binary_sensor.is_on: button2
                - lambda: 'return id(count1) < 3;'
            then:
                - switch.turn_on: relay2
                - delay: 200ms
                - switch.turn_off: relay2
                - lambda: 'id(count2) = id(count2) + 1;'
                - delay: 800ms

output:
  - platform: gpio
    id: buzzer
    pin: GPIO26

switch:
  - platform: gpio
    pin: GPIO18
    id: relay1
    name: relay1
  - platform: gpio
    pin: GPIO19
    id: relay2

mqtt:
  on_message:
    - topic: ${name}/beep
      then:
        - output.turn_on: buzzer
        - delay: 70ms
        - output.turn_off: buzzer
    - topic: ${name}/beep2
      then:
        - output.turn_on: buzzer
        - delay: 50ms
        - output.turn_off: buzzer
        - delay: 200ms
        - output.turn_on: buzzer
        - delay: 50ms
        - output.turn_off: buzzer
    - topic: ${name}/beeep
      then:
        - output.turn_on: buzzer
        - delay: 200ms
        - output.turn_off: buzzer
    - topic: ${name}/beeeep
      then:
        - output.turn_on: buzzer
        - delay: 1000ms
        - output.turn_off: buzzer
