esphome:
  name: test_esp
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    name: "Taster13"

switch:
  - platform: template
    name: "servo"
    turn_on_action:
      - servo.write:
          id: my_servo
          level: -100.0%
    turn_off_action:
      - servo.write:
          id: my_servo
          level: 0.0%

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 50Hz
    id: output_12

servo:
   - id: my_servo
     output: output_12

