substitutions:
  name: test-esp
  platform: ESP8266
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

light:
  - platform: rgb
    name: "Living Room Lights"
    red: r
    green: g
    blue: b

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'

esphome:
  on_boot:
    then:
      - rtttl.play: 'star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p'

output:
  - platform: esp8266_pwm
    id: r
    pin: 5
    max_power: 80%
  - platform: esp8266_pwm
    id: g
    pin: 4
    max_power: 80%
  - platform: esp8266_pwm
    id: b
    pin: 16
    max_power: 80%
  - platform: esp8266_pwm
    pin: 12
    id: rtttl_out

#  - platform: ledc
#    pin: 12
#    id: rtttl_out
#    inverted: True
#  - output.ledc.set_frequency:
#      id: rtttl_out
#      frequency: "1000Hz"
#  - output.set_level:
#      id: rtttl_out
#      level: "50%"