substitutions:
  name: test-esp
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

matrix_keypad:
  id: keypad
  rows:
    - pin: GPIO16
    - pin: GPIO14
    - pin: GPIO13
    - pin: GPIO12
  columns:
    - pin: GPIO05
    - pin: GPIO04
    - pin: GPIO02
  keys: "123456789*0#"
  has_diodes: false
#  on_key:
#    - lambda: ESP_LOGI("KEY", "key %d pressed", x);

# Example configuration entry
key_collector:
  - id: pincode
    source_id: keypad
#    min_length: 4
    max_length: 20
    end_keys: "#"
#    end_key_required: true
#    back_keys: "*"
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 5s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
    on_timeout:
      - logger.log:
          format: "input timeout: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]