substitutions:
  name: test-esp
  platform: ESP8266
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: 5
  scl: 4

globals:
  - id: time
    type: std::string
  - id: weather
    type: std::string

font:
  - file: 'Roboto-Medium.ttf'
    id: font1
    size: 37
  - file: 'Roboto-Medium.ttf'
    id: font2
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    lambda: |-
      it.printf(64,  0, id(font1), TextAlign::TOP_CENTER, id(time));
      it.printf(64, 64, id(font2), TextAlign::BOTTOM_CENTER, id(weather));

mqtt:
  on_json_message:
    - topic: ${name}/time
      then:
        lambda: |-
          id(time) = "15:17";
          id(weather) = "21° Sonne";
