esphome:
  name: test_esp
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

switch:
  - platform: template
    name: "servo"
    turn_on_action:
      - servo.write:
          id: my_servo
          level: -85.0%
    turn_off_action:
      - servo.write:
          id: my_servo
          level: 20.0%

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 50Hz
    id: output_12

servo:
   - id: my_servo
     output: output_12
     transition_length: 2s
     auto_detach_time: 1s

