esphome:
  name: test_esp
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

uart:
  - rx_pin: GPIO13
    baud_rate: 9600
    id: pms
  
  - rx_pin: GPIO14
    tx_pin: GPIO16
    baud_rate: 9600
    id: mh

i2c:
  sda: 5
  scl: 4

sensor:
  - platform: bme280
    address: 0x76
#    update_interval: 300s
    temperature:
      name: "temperature"
      id: "temperature"
      # filters:
      # - calibrate_linear:
      #   # - Map from sensor -> measured value
      #     - 12.9 -> 13.2
      #     - 17 -> 17
      #     - 19.4 -> 17.5
      #     - 24 -> 22
    humidity:
      name: "humidity"
      id: "humidity"
      # filters:
      # - calibrate_linear:
        # - Map from sensor -> measured value
        # - 0 -> 0  
        # - 72.7 -> 77.2
  - platform: pmsx003
    type: PMSX003
    uart_id: pms
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
      id: eco2
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
      id: tvoc
    update_interval: 1s
    # https://esphome.io/components/sensor/sgp30.html#calibrating-baseline
    # baseline:
    #   eco2_baseline: 0x92B7
    #   tvoc_baseline: 0x935A
    compensation:
        temperature_source: temperature
        humidity_source: humidity
  - platform: mhz19
    co2:
      name: "CO2"
    update_interval: 10s
    automatic_baseline_calibration: false
    uart_id: mh
