esphome:
  name: treppenhaus-gardrobe
  platform: ESP8266 # Shelly 1L Lichtschalter Gardrobe
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

switch:
  - platform: gpio
    pin: GPIO5
    name: relay1
    id: relay1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
    name: button2
    filters:
      - delayed_on_off: 10ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: relay1
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0
