esphome:
  name: treppenhaus_keller
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

switch:
  - platform: gpio
    pin: GPIO4
    name: relay1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: button1
    filters:
      - delayed_on_off: 50ms
