esphome:
  name: tuya
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

switch:
- platform: gpio
  pin: GPIO13
  name: switch13
- platform: gpio
  pin: GPIO12
  name: switch12
- platform: gpio
  pin: GPIO10
  name: switch10
- platform: gpio
  pin: GPIO9
  name: switch9
- platform: gpio
  pin: GPIO5
  name: switch5
- platform: gpio
  pin: GPIO3
  name: switch3
- platform: gpio
  pin: GPIO2
  name: switch2
- platform: gpio
  pin: GPIO1
  name: switch1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: "Taster4" # taster

