substitutions:
  name: wandschalter-wozi1
  platform: ESP8266 # shelly i3
  board: esp01_1m

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
    name: 'Switch 1'
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      number: GPIO14
    name: 'Switch 2'
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      number: GPIO13
    name: 'Switch 3'
    filters:
      - delayed_on_off: 100ms
