substitutions:
  name: wandschalter-wozi1
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    name: "links"
    filters:
      - delayed_on_off: 100ms
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "rechts"
    filters:
      - delayed_on_off: 100ms

