esphome:
  name: waschkueche_luefter
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: 5
  scl: 4
  
sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"

switch:
  - platform: gpio
    pin: GPIO12
    name: switch12