esphome:
  name: zwitscherbox
  board: esp12e
  platform: ESP8266
  on_boot:
    then:
      - dfplayer.play: 1
      - dfplayer.set_volume: 20

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: 5
  scl: 4
  scan: True

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

dfplayer:
  id: df_player
  on_finished_playback:
    then:
      logger.log: 'PLAYBACK FINISHED'

globals:
   - id: playing_stopped
     type: bool
     initial_value: 'false'

sensor:
  - platform: htu21d
    temperature:
      name: "temperature"
      filters:
      - calibrate_linear:
#        # - Map from sensor -> measured value
          - 2 -> 0
          - 23.4 -> 19.4
    humidity:
      name: "humidity"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode: INPUT_PULLUP
    name: "Previous"
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - dfplayer.play_previous:
        - logger.log: 'PREVIOUS'

  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
      mode: INPUT_PULLUP
    name: "Pause/Play"
    filters:
      - delayed_on_off: 100ms
    on_press:
        if:
          condition:
            lambda: |-
              return id(playing_stopped);
          then:
            - lambda: |-
                id(df_player).start();
                id(playing_stopped) = false;
            - logger.log: 'START'
          else:
            - lambda: |-
                id(df_player).pause();
                id(playing_stopped) = true;
            - logger.log: 'PAUSE'

  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
      mode: INPUT_PULLUP
    name: "Next"
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - dfplayer.play_next:
        - logger.log: 'NEXT'

  - platform: gpio
    pin:
      number: GPIO16
    name: "PIR"
    on_press:
      then:
        if:
          condition:
            lambda: |-
              return !id(playing_stopped) and !id(df_player).is_playing();
          then:
            - lambda: |-
                id(df_player).next();
            - logger.log: 'NEXT'
