esphome:
  name: zwitscherbox
  platform: ESP8266
  board: esp12e

packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  device_base: !include common/device_base.yaml

i2c:
  sda: 5
  scl: 4
  
sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "Temperatur"
      filters:
      - calibrate_linear:
        # - Map from sensor -> measured value
          - 2 -> 0
          - 22.2 -> 17.4
    humidity:
      name: "Luftfeuchtigkeit"

dfplayer:
  id: df_player

globals:
   - id: playing_stopped
     type: bool
     initial_value: 'false'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
    name: "Taster11"
    on_press:
      then:
        - dfplayer.play_previous:

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "Taster12"
    on_press:
        - lambda: |-
            id(playing_stopped) = true;
        - dfplayer.stop:
        - delay: 10min
        - lambda: |-
            id(playing_stopped) = false;

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    name: "Taster13"
    on_press:
      then:
        - dfplayer.play_next:

  - platform: gpio
    pin:
      number: GPIO04
    name: "PIR"
    on_press:
      then:
        if:
          condition:
            lambda: |-
              return !id(playing_stopped) and !id(df_player ).is_playing();
          then:
            - dfplayer.play_next:

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
