esphome:
  name: ${name}

esp32:
  board: ${board}
  framework:
    type: esp-idf

logger:

ota:
  platform: esphome

sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: WiFi Signal
